DROP EXTERNAL TABLE IF EXISTS customer_pxf;
CREATE EXTERNAL TABLE customer_pxf
(
 like customer
    ) LOCATION ('pxf://$NAMENODE:50070/$BASE/$SCALE/customer?profile=HdfsTextSimple')
FORMAT 'TEXT' (DELIMITER '|' NULL E'' FILL MISSING FIELDS) ENCODING 'latin1'
SEGMENT REJECT LIMIT 1 PERCENT;