DROP EXTERNAL TABLE IF EXISTS store_sales_pxf;
CREATE EXTERNAL TABLE store_sales_pxf
(
 like store_sales
) LOCATION ('pxf://$NAMENODE:50070/$BASE/$SIZE/store_sales?profile=HdfsTextSimple')
FORMAT 'TEXT' (DELIMITER '|' NULL E'' FILL MISSING FIELDS) ENCODING 'latin1'
SEGMENT REJECT LIMIT 1 PERCENT;