DROP EXTERNAL TABLE IF EXISTS web_returns_pxf;
CREATE EXTERNAL TABLE web_returns_pxf
(
  like web_returns
) LOCATION ('pxf://$NAMENODE:50070/$BASE/$SIZE/web_returns?profile=HdfsTextSimple')
FORMAT 'TEXT' (DELIMITER '|' NULL E'' FILL MISSING FIELDS) ENCODING 'latin1'
SEGMENT REJECT LIMIT 1 PERCENT;
