DROP EXTERNAL TABLE IF EXISTS web_site_pxf;
CREATE EXTERNAL TABLE web_site_pxf
(
   like web_site
) LOCATION ('pxf://$NAMENODE:50070/$BASE/$SCALE/web_site?profile=HdfsTextSimple')
FORMAT 'TEXT' (DELIMITER '|' NULL E'' FILL MISSING FIELDS) ENCODING 'latin1'
SEGMENT REJECT LIMIT 1 PERCENT;